language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer update
  - if [ "$TRAVIS_PHP_VERSION" != "5.4" ]; then composer require guzzlehttp/guzzle; fi;

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpspec run --format pretty
