language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpspec run --format pretty
